In [6]:
import numpy as np

In [7]:
# Gera alguns dados aleatórios.
data = np.random.randn(2, 3)

In [9]:
data

array([[ 1.28795111, -2.44471043,  1.3119766 ],
       [-0.38401648, -0.13287487, -1.4725039 ]])

In [10]:
data * 10

array([[ 12.8795111 , -24.44710432,  13.11976595],
       [ -3.84016478,  -1.32874872, -14.72503904]])

In [11]:
data + data

array([[ 2.57590222, -4.88942086,  2.62395319],
       [-0.76803296, -0.26574974, -2.94500781]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

## Criando ndarrays

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [20]:
arr2 = np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.empty((4, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])